In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import accuracy_score, classification_report

C:\anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [4]:
df = pd.read_csv('using_reviews (Autosaved).csv')
df.head()

,Unnamed: 0,reviews,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,sentiment
0,0,British Airways has confirmed itself as the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,1,✅ Worst BA experience. I was supposed to fl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2,✅ My daughter and I were denied boarding o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,3,✅ Despite boarding being the usual free for...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,4,"Flight cancelled, no crew! 9th September 20...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [5]:
df = df[['reviews', 'sentiment']]
df

                                               reviews  sentiment
0       British Airways has confirmed itself as the...        0.0
1    ✅    Worst BA experience. I was supposed to fl...        0.0
2    ✅     My daughter and I were denied boarding o...        0.0
3    ✅    Despite boarding being the usual free for...        0.0
4       Flight cancelled, no crew! 9th September 20...        0.0
..                                                 ...        ...
995  ✅     Boston to Nairobi via London. The only g...        NaN
996  ✅     Basel to San Fransisco via Heathrow. I'm...        NaN
997  ✅     London to Lyon. The flight has 1h 30 del...        NaN
998  ✅     London to Boston. I was seated next to a...        NaN
999  ✅    Stockholm to London. Standard configurati...        NaN

[1000 rows x 2 columns]

In [6]:
df.dropna()
df

                                               reviews  sentiment
0       British Airways has confirmed itself as the...        0.0
1    ✅    Worst BA experience. I was supposed to fl...        0.0
2    ✅     My daughter and I were denied boarding o...        0.0
3    ✅    Despite boarding being the usual free for...        0.0
4       Flight cancelled, no crew! 9th September 20...        0.0
..                                                 ...        ...
995  ✅     Boston to Nairobi via London. The only g...        NaN
996  ✅     Basel to San Fransisco via Heathrow. I'm...        NaN
997  ✅     London to Lyon. The flight has 1h 30 del...        NaN
998  ✅     London to Boston. I was seated next to a...        NaN
999  ✅    Stockholm to London. Standard configurati...        NaN

[1000 rows x 2 columns]

In [7]:
df_cleaned = df.dropna(subset=['sentiment'])
df_cleaned

                                              reviews  sentiment
0      British Airways has confirmed itself as the...        0.0
1   ✅    Worst BA experience. I was supposed to fl...        0.0
2   ✅     My daughter and I were denied boarding o...        0.0
3   ✅    Despite boarding being the usual free for...        0.0
4      Flight cancelled, no crew! 9th September 20...        0.0
..                                                ...        ...
95  ✅     Busy day at LHR and flight full. Lounge ...        1.0
96  ✅    Worst seats I have ever encountered in ec...        0.0
97    Top Ten REASONS to not use British Airways T...        0.0
98     Easy check in on the way to Heathrow. The f...        1.0
99  ✅     Online check in worked fine. Quick secur...        1.0

[100 rows x 2 columns]

In [8]:

df_cleaned['reviews'] = df_cleaned['reviews'].str.replace('[^a-zA-Z0-9\s]', '', regex=True)


print(df_cleaned)

                                              reviews  sentiment
0      British Airways has confirmed itself as the...        0.0
1       Worst BA experience I was supposed to fly ...        0.0
2        My daughter and I were denied boarding on...        0.0
3       Despite boarding being the usual free for ...        0.0
4      Flight cancelled no crew 9th September 2023...        0.0
..                                                ...        ...
95       Busy day at LHR and flight full Lounge cr...        1.0
96      Worst seats I have ever encountered in eco...        0.0
97    Top Ten REASONS to not use British Airways T...        0.0
98     Easy check in on the way to Heathrow The fl...        1.0
99       Online check in worked fine Quick securit...        1.0

[100 rows x 2 columns]

C:\Users\USER\AppData\Local\Temp/ipykernel_3468/1007173880.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['reviews'] = df_cleaned['reviews'].str.replace('[^a-zA-Z0-9\s]', '', regex=True)

In [9]:
df_cleaned.head()

                                             reviews  sentiment
0     British Airways has confirmed itself as the...        0.0
1      Worst BA experience I was supposed to fly ...        0.0
2       My daughter and I were denied boarding on...        0.0
3      Despite boarding being the usual free for ...        0.0
4     Flight cancelled no crew 9th September 2023...        0.0

In [10]:
df_cleaned['sentiment'] = df_cleaned['sentiment'].astype(int)
df_cleaned.head()

C:\Users\USER\AppData\Local\Temp/ipykernel_3468/3406000897.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['sentiment'] = df_cleaned['sentiment'].astype(int)

                                             reviews  sentiment
0     British Airways has confirmed itself as the...          0
1      Worst BA experience I was supposed to fly ...          0
2       My daughter and I were denied boarding on...          0
3      Despite boarding being the usual free for ...          0
4     Flight cancelled no crew 9th September 2023...          0

In [25]:
reviews = df['reviews'].astype(str)
sentiment = df['sentiment']

# Tokenization and Padding for Text Data
max_words = 100
max_len = 25

tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)

text_sequences = tokenizer.texts_to_sequences(reviews)
text_padded = pad_sequences(text_sequences, maxlen=max_len, padding='post')

# Additional preprocessing for numerical features (if any)
numerical_features = df.drop(['sentiment', 'reviews'], axis=1)  # Assuming 'text' and 'label' are column names
# ... additional preprocessing for numerical features if needed

# Combine processed text data and numerical features
X_combined = text_padded  # Combine with numerical features if applicable

# Data Splitting
X_train, X_test, y_train, y_test = train_test_split(
    X_combined, sentiment, test_size=0.2, random_state=42
)

# Build Bidirectional LSTM Model
embedding_dim = 50

model = Sequential()
model.add(Embedding(input_dim=max_words, output_dim=embedding_dim, input_length=max_len))
model.add(Bidirectional(LSTM(100)))#recurrent_dropout=0.2
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Model Training
model.fit(X_train, y_train, epochs=50, batch_size=64, validation_split=0.2)

# Making Predictions
y_pred_prob = model.predict(X_test)
y_pred = [1 if prob > 0.5 else 0 for prob in y_pred_prob]

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

Epoch 1/50
10/10 [==============================] - 16s 821ms/step - loss: 0.1954 - accuracy: 0.0109 - val_loss: -1.0936 - val_accuracy: 0.0250
Epoch 2/50
10/10 [==============================] - 5s 495ms/step - loss: -5.6791 - accuracy: 0.0094 - val_loss: -9.2526 - val_accuracy: 0.0250
Epoch 3/50
10/10 [==============================] - 5s 502ms/step - loss: -11.9640 - accuracy: 0.0094 - val_loss: -13.5500 - val_accuracy: 0.0250
Epoch 4/50
10/10 [==============================] - 4s 473ms/step - loss: -15.9571 - accuracy: 0.0094 - val_loss: -16.6307 - val_accuracy: 0.0250
Epoch 5/50
10/10 [==============================] - 5s 528ms/step - loss: -18.7679 - accuracy: 0.0094 - val_loss: -18.9208 - val_accuracy: 0.0250
Epoch 6/50
10/10 [==============================] - 5s 481ms/step - loss: -21.0538 - accuracy: 0.0094 - val_loss: -20.9110 - val_accuracy: 0.0250
Epoch 7/50
10/10 [==============================] - 5s 458ms/step - loss: -23.0586 - accuracy: 0.0094 - val_loss: -22.8099 - val_accuracy: 0.0250
Epoch 8/50
10/10 [==============================] - 3s 312ms/step - loss: -25.0594 - accuracy: 0.0094 - val_loss: -24.6041 - val_accuracy: 0.0250
Epoch 9/50
10/10 [==============================] - 4s 424ms/step - loss: -26.9329 - accuracy: 0.0094 - val_loss: -26.3904 - val_accuracy: 0.0250
Epoch 10/50
10/10 [==============================] - 4s 352ms/step - loss: -28.8405 - accuracy: 0.0094 - val_loss: -28.1407 - val_accuracy: 0.0250
Epoch 11/50
10/10 [==============================] - 4s 416ms/step - loss: -30.6466 - accuracy: 0.0094 - val_loss: -29.8903 - val_accuracy: 0.0250
Epoch 12/50
10/10 [==============================] - 5s 523ms/step - loss: -32.5192 - accuracy: 0.0094 - val_loss: -31.5650 - val_accuracy: 0.0250
Epoch 13/50
10/10 [==============================] - 5s 588ms/step - loss: -34.2744 - accuracy: 0.0094 - val_loss: -33.2528 - val_accuracy: 0.0250
Epoch 14/50
10/10 [==============================] - 6s 558ms/step - loss: -36.0536 - accuracy: 0.0094 - val_loss: -34.9200 - val_accuracy: 0.0250
Epoch 15/50
10/10 [==============================] - 5s 533ms/step - loss: -37.8139 - accuracy: 0.0094 - val_loss: -36.5825 - val_accuracy: 0.0250
Epoch 16/50
10/10 [==============================] - 5s 486ms/step - loss: -39.5777 - accuracy: 0.0094 - val_loss: -38.2365 - val_accuracy: 0.0250
Epoch 17/50
10/10 [==============================] - 4s 351ms/step - loss: -41.3231 - accuracy: 0.0094 - val_loss: -39.8835 - val_accuracy: 0.0250
Epoch 18/50
10/10 [==============================] - 5s 455ms/step - loss: -43.0842 - accuracy: 0.0094 - val_loss: -41.5012 - val_accuracy: 0.0250
Epoch 19/50
10/10 [==============================] - 4s 434ms/step - loss: -44.7889 - accuracy: 0.0094 - val_loss: -43.1328 - val_accuracy: 0.0250
Epoch 20/50
10/10 [==============================] - 3s 351ms/step - loss: -46.5138 - accuracy: 0.0094 - val_loss: -44.7579 - val_accuracy: 0.0250
Epoch 21/50
10/10 [==============================] - 5s 486ms/step - loss: -48.2241 - accuracy: 0.0094 - val_loss: -46.3973 - val_accuracy: 0.0250
Epoch 22/50
10/10 [==============================] - 5s 494ms/step - loss: -49.9712 - accuracy: 0.0094 - val_loss: -48.0157 - val_accuracy: 0.0250
Epoch 23/50
10/10 [==============================] - 5s 581ms/step - loss: -51.6919 - accuracy: 0.0094 - val_loss: -49.6901 - val_accuracy: 0.0250
Epoch 24/50
10/10 [==============================] - 5s 496ms/step - loss: -53.4860 - accuracy: 0.0094 - val_loss: -51.3419 - val_accuracy: 0.0250
Epoch 25/50
10/10 [==============================] - 6s 543ms/step - loss: -55.2321 - accuracy: 0.0094 - val_loss: -52.9622 - val_accuracy: 0.0250
Epoch 26/50
10/10 [==============================] - 5s 535ms/step - loss: -56.9525 - accuracy: 0.0094 - val_loss: -54.5794 - val_accuracy: 0.0250
Epoch 27/50
10/10 [==============================] - 5s 540ms/step - loss: -58.6652 - accuracy: 0.0094 - val_loss: -56.1942 - val_accuracy: 0.0250
Epoch 28/50
10/10 [==============================] - 6s 608ms/step - loss: -60.3744 - accuracy: 0.0094 - val_loss: -57.8042 - val_accuracy: 0.0250
Epoch 29/50
10/10 [==============================] - 5s 542ms/step - loss: -62.0816 - accuracy: 0.0094 - val_loss: -59.4072 - val_accuracy: 0.0250
Epoch 30/50
10/10 [==============================] - 5s 503ms/step - loss: -63.7718 - accuracy: 0.0094 - val_loss: -61.0142 - val_accuracy: 0.0250
Epoch 31/50
10/10 [==============================] - 5s 445ms/step - loss: -65.4692 - accuracy: 0.0094 - val_loss: -62.6152 - val_accuracy: 0.0250
Epoch 32/50
10/10 [==============================] - 5s 498ms/step - loss: -67.1681 - accuracy: 0.0094 - val_loss: -64.2073 - val_accuracy: 0.0250
Epoch 33/50
10/10 [==============================] - 5s 494ms/step - loss: -68.8633 - accuracy: 0.0094 - val_loss: -65.8006 - val_accuracy: 0.0250
Epoch 34/50
10/10 [==============================] - 5s 498ms/step - loss: -70.5638 - accuracy: 0.0094 - val_loss: -67.4088 - val_accuracy: 0.0250
Epoch 35/50
10/10 [==============================] - 5s 484ms/step - loss: -72.2568 - accuracy: 0.0094 - val_loss: -69.0267 - val_accuracy: 0.0250
Epoch 36/50
10/10 [==============================] - 4s 440ms/step - loss: -73.9771 - accuracy: 0.0094 - val_loss: -70.6251 - val_accuracy: 0.0250
Epoch 37/50
10/10 [==============================] - 4s 368ms/step - loss: -75.6653 - accuracy: 0.0094 - val_loss: -72.2294 - val_accuracy: 0.0250
Epoch 38/50
10/10 [==============================] - 4s 397ms/step - loss: -77.3474 - accuracy: 0.0094 - val_loss: -73.8404 - val_accuracy: 0.0250
Epoch 39/50
10/10 [==============================] - 3s 332ms/step - loss: -79.0563 - accuracy: 0.0094 - val_loss: -75.4315 - val_accuracy: 0.0250
Epoch 40/50
10/10 [==============================] - 4s 426ms/step - loss: -80.7548 - accuracy: 0.0094 - val_loss: -77.0098 - val_accuracy: 0.0250
Epoch 41/50
10/10 [==============================] - 5s 498ms/step - loss: -82.4231 - accuracy: 0.0094 - val_loss: -78.6011 - val_accuracy: 0.0250
Epoch 42/50
10/10 [==============================] - 4s 444ms/step - loss: -84.0965 - accuracy: 0.0094 - val_loss: -80.1971 - val_accuracy: 0.0250
Epoch 43/50
10/10 [==============================] - 5s 508ms/step - loss: -85.8004 - accuracy: 0.0094 - val_loss: -81.7692 - val_accuracy: 0.0250
Epoch 44/50
10/10 [==============================] - 5s 487ms/step - loss: -87.4735 - accuracy: 0.0094 - val_loss: -83.3440 - val_accuracy: 0.0250
Epoch 45/50
10/10 [==============================] - 5s 504ms/step - loss: -89.1489 - accuracy: 0.0094 - val_loss: -84.9177 - val_accuracy: 0.0250
Epoch 46/50
10/10 [==============================] - 5s 486ms/step - loss: -90.8165 - accuracy: 0.0094 - val_loss: -86.4959 - val_accuracy: 0.0250
Epoch 47/50
10/10 [==============================] - 5s 483ms/step - loss: -92.4871 - accuracy: 0.0094 - val_loss: -88.0753 - val_accuracy: 0.0250
Epoch 48/50
10/10 [==============================] - 6s 557ms/step - loss: -94.1569 - accuracy: 0.0094 - val_loss: -89.6591 - val_accuracy: 0.0250
Epoch 49/50
10/10 [==============================] - 5s 532ms/step - loss: -95.8642 - accuracy: 0.0094 - val_loss: -91.2376 - val_accuracy: 0.0250
Epoch 50/50
10/10 [==============================] - 5s 465ms/step - loss: -97.5302 - accuracy: 0.0094 - val_loss: -92.8482 - val_accuracy: 0.0250
7/7 [==============================] - 4s 83ms/step
Accuracy: 0.02
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        16
           1       0.02      1.00      0.04         4
           2       0.00      0.00      0.00       180

    accuracy                           0.02       200
   macro avg       0.01      0.33      0.01       200
weighted avg       0.00      0.02      0.00       200

C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

C:\anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
X = df_cleaned['reviews']
y = df_cleaned['sentiment']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
tfidf_vectorizer = TfidfVectorizer(max_features=100)  # Adjust max_features based on your dataset
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [13]:
svm_model = SVC(kernel='linear')  # 'linear' kernel is often used for text classification
svm_model.fit(X_train_tfidf, y_train)

SVC(kernel='linear')

In [14]:

y_pred = svm_model.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

classification_rep = classification_report(y_test, y_pred)
print("Classification Report:\n", classification_rep)

Accuracy: 0.90
Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95        18
           1       0.00      0.00      0.00         2

    accuracy                           0.90        20
   macro avg       0.45      0.50      0.47        20
weighted avg       0.81      0.90      0.85        20

C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [15]:
new_example = ['good crew']


new_example_tfidf = tfidf_vectorizer.transform(new_example)


y_pred = svm_model.predict(new_example_tfidf)

print(f"Predicted Label: {y_pred}")

Predicted Label: [1]

In [16]:
new_example = ['unresonable flight attendants']


new_example_tfidf = tfidf_vectorizer.transform(new_example)


y_pred = svm_model.predict(new_example_tfidf)

print(f"Predicted Label: {y_pred}")

Predicted Label: [0]

In [17]:
new_example = ['they lost my luggage']


new_example_tfidf = tfidf_vectorizer.transform(new_example)


y_pred = svm_model.predict(new_example_tfidf)

print(f"Predicted Label: {y_pred}")

Predicted Label: [0]

# the data was just too small for using deep Neural network

In [18]:
new_example = ['good crew, but they lost my luggage']


new_example_tfidf = tfidf_vectorizer.transform(new_example)


y_pred = svm_model.predict(new_example_tfidf)

print(f"Predicted Label: {y_pred}")

Predicted Label: [0]